### ISSUE TITLE
PWA Application (add-to-homescreen option)

### ISSUE THREAD

**Issue by mauriziomolle** [Ceeresa/autocertificazione#107]
https://github.com/cubiq/add-to-homescreen
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
https://caniuse.com/web-app-manifest

**Comment by DavidePastore** [comment]
Associated with #138.

**Comment by mauriziomolle** [comment]
We decided to go for a 3 click video solution
