### ISSUE TITLE
Add html tags to allow easier fulfilment of text fields

### ISSUE THREAD

**Issue by tom139** [Ceeresa/autocertificazione#220]
HTML defines the `autocomplete` attribute (see [The autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)) which can be used by browsers to suggest inputs to the users.

In addition to adding this attributes it could be useful to disable spellchecks on the document number field.

---

Thank you for the effort you put in this project; I hope you accept contributions and will make a PR in the next couple minutes.

**Comment by DavidePastore** [comment]
Closed by #222.
